'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_BACKEND_URL||'https://nur-oqiw.onrender.com';
export default function ProfilePage(){
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false,count=0;const boot=()=>{if(cancelled)return;const raw=window.Telegram?.WebApp?.initData||'';if(!raw){if(count++<24){setTimeout(boot,250);return;}setError('Profilni ko‘rish uchun Telegram bot ichidan oching.');return;}fetch(API+'/api/test/profile',{cache:'no-store',headers:{Authorization:'tma '+raw}}).then(r=>r.json()).then(j=>{if(cancelled)return;if(j.ok)setData(j);else setError('Profil ma’lumotlari olinmadi.');}).catch(()=>{if(!cancelled)setError('Internet aloqasini tekshiring.');});};boot();return()=>{cancelled=true};},[]);
 if(error)return <main className="profile-error"><h1>Profil</h1><p>{error}</p><a href="/">Bosh sahifa</a></main>;
 if(!data)return <main className="profile-shell"><section className="profile-card profile-wrap">Profil yuklanmoqda…</section></main>;
 return <main className="profile-shell"><div className="profile-wrap"><section className="profile-card"><div className="profile-hero">{data.photo_url?<img className="profile-avatar" src={data.photo_url} alt="Profil rasmi"/>:<div className="profile-avatar"/>}<div><h1>{data.full_name||'Foydalanuvchi'}</h1><p>Shaxsiy profil</p></div></div></section><section className="profile-card"><h2>Testlarim</h2>{data.tests.length?data.tests.map((t,i)=><div className="history-row" key={t.test_id+'-'+i}><div className="history-main"><strong>{t.test_name}</strong><small>Kod: {t.code||'—'} · {t.submitted?'Yakunlangan':'Jarayonda'}</small></div><div className="history-score">{t.submitted?t.score.toFixed(2)+'%':'—'}</div></div>):<p className="profile-muted">Hozircha test natijasi yo‘q.</p>}</section></div><nav className="bottom-glass-nav" aria-label="Asosiy navigatsiya"><a className="nav-item" href="/"><span>⌂</span><small>Test</small></a><a className="nav-item active" href="/profile"><span>◉</span><small>Profil</small></a><a className="nav-item" href={data.tests?.[0]?.code?`/ranking?code=${encodeURIComponent(data.tests[0].code)}`:"/ranking"}><span>♜</span><small>Reyting</small></a></nav></main>;
}