'use client';
import {useEffect,useState} from 'react';
const API=process.env.NEXT_PUBLIC_BACKEND_URL||'https://nur-oqiw.onrender.com';
function Avatar({src,name}){return src?<img src={src} alt={name}/>:<img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Ccircle cx='32' cy='32' r='32' fill='%23e7eaf0'/%3E%3Ccircle cx='32' cy='24' r='11' fill='%239ba4b1'/%3E%3Cpath d='M10 60c2-14 10-21 22-21s20 7 22 21' fill='%239ba4b1'/%3E%3C/svg%3E" alt={name}/>}
export default function RankingPage(){
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let cancelled=false,count=0;const boot=()=>{if(cancelled)return;const raw=window.Telegram?.WebApp?.initData||'';if(!raw){if(count++<24){setTimeout(boot,250);return;}setError('Reytingni ko‘rish uchun Telegram bot ichidan oching.');return;}const code=new URLSearchParams(window.location.search).get('code')||'';fetch(API+'/api/test/ranking?code='+encodeURIComponent(code),{cache:'no-store',headers:{Authorization:'tma '+raw}}).then(r=>r.json()).then(j=>{if(cancelled)return;if(j.ok)setData(j);else setError('Test kodi topilmadi. Avval test sahifasidan reytingni oching.');}).catch(()=>{if(!cancelled)setError('Internet aloqasini tekshiring.');});};boot();return()=>{cancelled=true};},[]);
 if(error)return <main className="profile-error"><h1>Reyting</h1><p>{error}</p><a href="/">Test sahifasi</a></main>;
 if(!data)return <main className="ranking-shell"><section className="ranking-card ranking-wrap">Reyting yuklanmoqda…</section></main>;
 const top=data.ranking||[],podium=[top[1],top[0],top[2]].filter(Boolean);
 return <main className="ranking-shell"><div className="ranking-wrap"><nav className="page-nav"><a href="/">Test</a><a href="/profile">Profil</a></nav><section className="ranking-card"><p className="profile-muted">TEST REYTINGI · {data.code}</p><h1>{data.test_name}</h1><p className="profile-muted">Yakunlaganlar: {data.total} · TOP 15</p>{podium.length?<div className="ranking-podium">{podium.map((u)=><div key={u.rank} className={'podium-card '+(u.rank===1?'first':u.rank===2?'second':'third')}><Avatar src={u.photo_url} name={u.full_name}/><strong>{u.full_name}</strong><small>{u.rank===1?'GOLD':u.rank===2?'SILVER':'BRONZE'} · {u.score.toFixed(2)}%</small></div>)}</div>:<div className="ranking-empty">Hali yakunlangan natijalar yo‘q.</div>}</section><section className="ranking-card"><h2>TOP 15</h2>{top.map(u=><div className="ranking-row" key={u.rank}><span className={'rank-number '+(u.rank===1?'gold':u.rank===2?'silver':u.rank===3?'bronze':'')}>{u.rank}</span><Avatar src={u.photo_url} name={u.full_name}/><div className="ranking-main"><strong>{u.full_name}</strong><small>{u.grade||'Baho yo‘q'}</small></div><strong className="history-score">{u.score.toFixed(2)}%</strong></div>)}</section></div></main>;
}