'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {NUR_LOGO_DATA} from '../logo-data';
const API=process.env.NEXT_PUBLIC_BACKEND_URL||'https://nur-oqiw.onrender.com';
function Logo(){return <img src={NUR_LOGO_DATA} alt="Nur oqıw orayı" className="brand-logo-image"/>}
function Choice({q,answer,result,onChoose}){const locked=answer!==undefined;return <section className="q-card"><div className="q-top"><span>Savol {q.id}</span><span>{q.kind==='written'?'Yozma':'Variant'}</span></div>{q.kind==='written'?<p className="external-note">Javobni PDF/materialdagi savolga qarab yozing.</p>:<><h2 className="number-only">{q.id}-savol</h2><div className="choice-grid">{['A','B','C','D'].map(x=>{const selected=answer===x;const cls=locked?(selected?(result==='correct'?'picked-correct':'picked-wrong'):'choice-dim'):'';return <button type="button" key={x} disabled={locked} className={`choice-btn ${cls}`} onClick={()=>onChoose(q.id,x)}><span className="choice-letter">{x}</span></button>})}</div>{result==='correct'&&<div className="answer-result correctText">To‘g‘ri javob</div>}{result==='wrong'&&<div className="answer-result wrongText">Noto‘g‘ri javob</div>}</>}</section>}
export default function Test(){
 const[initData,setInitData]=useState(''),[qs,setQs]=useState([]),[answers,setAnswers]=useState({}),[results,setResults]=useState({}),[status,setStatus]=useState('loading'),[msg,setMsg]=useState(''),[score,setScore]=useState(null),[name,setName]=useState(''),[testName,setTestName]=useState(''),[endsAt,setEndsAt]=useState(null),[index,setIndex]=useState(0),[now,setNow]=useState(Date.now());
 const code=useMemo(()=>{try{return new URLSearchParams(window.location.search).get('code')||''}catch{return ''}},[]);
 const load=useCallback(async raw=>{if(!raw){setStatus('blocked');setMsg('Telegram sessiyasi topilmadi. Bot ichidan oching.');return}try{const s=await fetch(`${API}/api/test/state?initData=${encodeURIComponent(raw)}&code=${encodeURIComponent(code)}`,{cache:'no-store'});const sj=await s.json();if(!sj.ok){setStatus(sj.error==='already_submitted'?'done':'blocked');setMsg(sj.error==='test_closed'?'Test yopiq.':sj.error==='test_not_found'?'Test kodi topilmadi.':sj.error==='already_submitted'?'Bu test avval yakunlangan.':sj.error==='registration_required'?'Avval botda ro‘yxatdan o‘ting, keyin Mini Appni qayta oching.':'Test sessiyasi topilmadi.');setScore(sj.score??null);setName(sj.full_name||'');setTestName(sj.test_name||'');return}const r=await fetch(`${API}/api/test/questions?initData=${encodeURIComponent(raw)}&code=${encodeURIComponent(code)}`,{cache:'no-store'});const qj=await r.json();if(!qj.ok)throw new Error();setQs(qj.questions||[]);setAnswers(sj.answers||{});setName(sj.full_name||'');setTestName(sj.test_name||'');setEndsAt(sj.ends_at);setStatus('test')}catch{setStatus('blocked');setMsg('Testni yuklashda xatolik.')}},[code]);
 useEffect(()=>{const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const raw=tg?.initData||'';setInitData(raw);load(raw);const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[load]);
 async function choose(id,value){if(answers[id]!==undefined)return;try{const r=await fetch(API+'/api/test/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,code,question_id:id,answer:value})});const j=await r.json();if(j.ok){setAnswers(a=>({...a,[id]:value}));setResults(a=>({...a,[id]:j.correct?'correct':'wrong'}));}}catch{setMsg('Javobni saqlashda xatolik.')}}
 const finish=useCallback(async()=>{if(status!=='test')return;try{const r=await fetch(API+'/api/test/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,code})});const j=await r.json();if(j.ok){setScore(j.score);setStatus('done');setMsg('Test muvaffaqiyatli yakunlandi.')}else setMsg(j.error==='test_closed'?'Test yopildi.':'Testni yakunlab bo‘lmadi.')}catch{setMsg('Natijani saqlashda xatolik.')}},[status,initData,code]);
 const seconds=endsAt?Math.max(0,Math.floor((new Date(endsAt).getTime()-now)/1000)):0;useEffect(()=>{if(status==='test'&&endsAt&&seconds<=0)finish()},[status,endsAt,seconds,finish]);
 if(status==='loading')return <main className="screen"><section className="glass-card"><Logo/><h1>Yuklanmoqda</h1><p>Test ma'lumotlari olinmoqda...</p></section></main>;
 if(status!=='test')return <main className="screen"><section className="glass-card"><Logo/><h1>{status==='done'?'Test yakunlandi':'Test holati'}</h1>{testName&&<p className="test-title">{testName}</p>}{name&&<p className="user-name">{name}</p>}<p>{msg}</p>{score!==null&&<strong className="final-score">{Number(score).toFixed(2)} ball</strong>}</section></main>;
 const q=qs[index];return <div className="test-shell"><header className="test-header"><div><b>{testName||'NUR O‘QIW ORAYI'}</b><small>{name||'Test'}</small></div><span>{index+1}/{qs.length}</span></header><div className="progress-track"><i style={{width:`${qs.length?((index+1)/qs.length)*100:0}%`}}/></div><div className="live-bar"><span>Qolgan vaqt</span><strong>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong></div><main className="test-wrap"><section className="test-intro"><small>{code||'TEST'}</small><h1>{testName||'Test'}</h1><p>Savol PDF/materialda. Bu yerda faqat javob variantini tanlang.</p></section>{q?<Choice q={q} answer={answers[q.id]} result={results[q.id]} onChoose={choose}/>:<section className="q-card"><h2>Savollar topilmadi.</h2></section>}<div className="question-nav"><button disabled={index===0} onClick={()=>setIndex(i=>i-1)}>Oldingi</button><span>{index+1} / {qs.length}</span>{index<qs.length-1?<button onClick={()=>setIndex(i=>i+1)}>Keyingi</button>:<button className="finish" onClick={finish}>Testni yakunlash</button>}</div></main></div>}
