'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';

const SYMBOLS=['√','²','³','π','÷','×','−','≤','≥','≠','∞','±','(',')','sin','cos','tan','log','ln','|x|','xⁿ'];
const API=process.env.NEXT_PUBLIC_BACKEND_URL||'https://nur-oqiw.onrender.com';
function Logo(){return <div className="brand-logo-wrap" aria-label="Nur oqiw"><img src="/logo.png" alt="Nur oqiw" className="brand-logo-image" onError={e=>{e.currentTarget.style.display='none';e.currentTarget.nextSibling.style.display='grid'}}/><span className="brand-logo-fallback">N</span></div>}
function Keypad({on,disabled}){return <div className="keypad">{SYMBOLS.map(x=><button type="button" key={x} disabled={disabled} onClick={()=>on(x)}>{x}</button>)}</div>}
function Choice({q,answer,result,onChoose}){const locked=answer!==undefined;return <section className="q-card"><div className="q-top"><span>Savol {q.id}</span><span>Variantli</span></div><h2>{q.question}</h2>{q.image_url&&<img className="question-image" src={q.image_url} alt="Savol rasmi" loading="lazy"/>}<div className="choice-grid">{(q.options||[]).slice(0,4).map((v,i)=>{const letter=String.fromCharCode(65+i);const selected=answer===v;const cls=locked?(selected?(result==='correct'?'picked-correct':'picked-wrong'):'choice-dim'):'';return <button type="button" key={i} disabled={locked} className={`choice-btn ${cls}`} onClick={()=>onChoose(q.id,v)}><span className="choice-letter">{letter}</span><span className="choice-text">{v}</span></button>})}</div>{result==='correct'&&<div className="answer-result correctText">To‘g‘ri javob</div>}{result==='wrong'&&<div className="answer-result wrongText">Noto‘g‘ri javob</div>}</section>}
function Written({q,answer,onSave,initData,code}){const[value,setValue]=useState(answer||'');const[busy,setBusy]=useState(false);async function accept(){if(!value.trim()||answer||busy)return;setBusy(true);try{const r=await fetch(API+'/api/test/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,code,question_id:q.id,answer:value.trim()})});const j=await r.json();if(j.ok)onSave(q.id,value.trim())}finally{setBusy(false)}}return <section className="q-card"><div className="q-top"><span>Savol {q.id}</span><span>Yozma</span></div><h2>{q.question}</h2>{q.image_url&&<img className="question-image" src={q.image_url} alt="Savol rasmi"/>}<input className="answer-input" value={value} disabled={!!answer} onChange={e=>setValue(e.target.value)} placeholder="Javobni kiriting"/><Keypad disabled={!!answer||busy} on={x=>setValue(v=>v+x)}/><button className="accept-answer" disabled={!!answer||busy||!value.trim()} onClick={accept}>{answer?'Javob qabul qilingan':busy?'Saqlanmoqda…':'Javobni qabul qilish'}</button></section>}

export default function Test(){
 const[initData,setInitData]=useState(''),[qs,setQs]=useState([]),[answers,setAnswers]=useState({}),[results,setResults]=useState({}),[status,setStatus]=useState('loading'),[msg,setMsg]=useState(''),[score,setScore]=useState(null),[fullName,setFullName]=useState(''),[testName,setTestName]=useState(''),[endsAt,setEndsAt]=useState(null),[index,setIndex]=useState(0),[now,setNow]=useState(Date.now());
 const autoFinished=useRef(false);const code=useMemo(()=>{try{return new URLSearchParams(window.location.search).get('code')||''}catch{return ''}},[]);
 const load=useCallback(async(data)=>{if(!data){setStatus('blocked');setMsg('Telegram sessiyasi topilmadi. Bot ichidan testni oching.');return}setStatus('loading');try{const suffix=code?'&code='+encodeURIComponent(code):'';const[qr,sr]=await Promise.all([fetch(API+'/api/test/questions?initData='+encodeURIComponent(data)+suffix,{cache:'no-store'}),fetch(API+'/api/test/state?initData='+encodeURIComponent(data)+suffix,{cache:'no-store'})]);const qj=await qr.json(),sj=await sr.json();if(qj.ok)setQs(qj.questions||[]);if(!sj.ok){setFullName(sj.full_name||'');setScore(sj.score??null);setTestName(sj.test_name||'');setMsg(sj.error==='already_submitted'?'Bu test avval yakunlangan.':sj.error==='test_closed'?'Test hozir yopiq.':sj.error==='test_not_found'?'Test kodi topilmadi.':'Test sessiyasi topilmadi.');setStatus(sj.error==='already_submitted'?'done':'blocked');return}setAnswers(sj.answers||{});setFullName(sj.full_name||'');setTestName(sj.test_name||'');setEndsAt(sj.ends_at);setStatus('test')}catch{setStatus('blocked');setMsg('Testni yuklashda xatolik. Qayta urinib ko‘ring.')}},[code]);
 useEffect(()=>{const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();const raw=tg?.initData||'';setInitData(raw);load(raw);const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[load]);
 async function choose(id,value){if(answers[id]!==undefined||status!=='test')return;try{const r=await fetch(API+'/api/test/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,code,question_id:id,answer:value})});const j=await r.json();if(j.ok){setAnswers(a=>({...a,[id]:value}));setResults(a=>({...a,[id]:j.correct?'correct':'wrong'}));try{window.Telegram?.WebApp?.HapticFeedback?.notificationOccurred(j.correct?'success':'error')}catch{}}else if(j.error==='test_closed'){setStatus('expired');setMsg('Test yopildi.')}else if(j.error==='answer_locked'){setResults(a=>({...a,[id]:j.correct?'correct':'wrong'}))}}catch{setMsg('Javobni saqlashda xatolik.')}}
 const finish=useCallback(async()=>{if(status!=='test'||autoFinished.current)return;autoFinished.current=true;try{const r=await fetch(API+'/api/test/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,code})});const j=await r.json();if(j.ok){setScore(j.score);setStatus('done');setMsg('Test muvaffaqiyatli yakunlandi.');try{window.Telegram?.WebApp?.HapticFeedback?.notificationOccurred('success')}catch{}}else{setStatus('expired');setMsg(j.error==='test_closed'?'Test vaqti tugadi.':'Testni yakunlab bo‘lmadi.')}}catch{autoFinished.current=false;setMsg('Natijani saqlashda xatolik.')}} ,[status,initData,code]);
 const answered=Object.keys(answers).length,total=qs.length,q=qs[index],secondsLeft=endsAt?Math.max(0,Math.floor((new Date(endsAt).getTime()-now)/1000)):0,progress=total?Math.round(answered/total*100):0;
 useEffect(()=>{if(status==='test'&&endsAt&&secondsLeft<=0)finish()},[status,endsAt,secondsLeft,finish]);
 if(status==='loading')return <main className="screen"><section className="glass-card"><Logo/><b>NUR O‘QIW ORAYI</b><h1>Yuklanmoqda</h1><p>Test ma’lumotlari olinmoqda…</p></section></main>;
 if(status!=='test')return <main className="screen"><section className="glass-card"><Logo/><b>NUR O‘QIW ORAYI</b><h1>{status==='done'?'Test yakunlandi':'Test holati'}</h1>{testName&&<p className="test-title">{testName}</p>}{fullName&&<p className="user-name">{fullName}</p>}<p>{msg}</p>{score!==null&&<strong className="final-score">{Number(score).toFixed(2)} ball</strong>}</section></main>;
 return <div className="test-shell"><header className="test-header"><div><b>{testName||'NUR O‘QIW ORAYI'}</b><small>{fullName||'Test'}</small></div><span>{answered}/{total}</span></header><div className="progress-track"><i style={{width:`${progress}%`}}/></div><div className="live-bar"><span>Qolgan vaqt</span><strong>{Math.floor(secondsLeft/60)}:{String(secondsLeft%60).padStart(2,'0')}</strong></div><main className="test-wrap"><section className="test-intro"><small>{code||'TEST'}</small><h1>{testName||'Test'}</h1><p>{index+1}-savol / {total} · Javob tanlang va u bloklanadi</p></section>{q?(q.kind==='written'?<Written key={q.id} q={q} answer={answers[q.id]} code={code} onSave={(id,v)=>setAnswers(a=>({...a,[id]:v}))} initData={initData}/>:<Choice key={q.id} q={q} answer={answers[q.id]} result={results[q.id]} onChoose={choose}/>):<section className="q-card"><h2>Savollar topilmadi.</h2></section>}<div className="question-nav"><button disabled={index<=0} onClick={()=>setIndex(i=>i-1)}>Oldingi</button><span>{index+1} / {total}</span>{index<total-1?<button onClick={()=>setIndex(i=>i+1)}>Keyingi</button>:<button className="finish" onClick={finish}>Testni yakunlash</button>}</div></main></div>}
