'use client';
import {useEffect,useState} from 'react';

function Keypad({on}){return <div className="keypad">{['√','²','³','π','÷','×','−','≤','≥','(',')'].map(x=><button type="button" key={x} onClick={()=>on(x)}>{x}</button>)}</div>}
function Choice({q,answer,result,onChoose}){return <section className="q"><h2>{q.question}</h2><div className="answers">{(q.options||[]).slice(0,4).map((v,i)=><button type="button" key={i} disabled={answer!==undefined} className={answer!==undefined?(answer===v?(result==='correct'?'correct':'wrong'):'dim'):''} onClick={()=>onChoose(q.id,v)}>{String.fromCharCode(65+i)}. {v}</button>)}</div>{result==='correct'&&<div className="answer-result correctText">To‘g‘ri javob</div>}{result==='wrong'&&<div className="answer-result wrongText">Noto‘g‘ri javob</div>}</section>}
function Written({q,answer,save,initData}){const [v,setV]=useState(answer||'');const [busy,setBusy]=useState(false);async function accept(){if(!v.trim()||answer||busy)return;setBusy(true);try{const r=await fetch((process.env.NEXT_PUBLIC_BACKEND_URL||'')+'/api/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,question_id:q.id,answer:v})});const j=await r.json();if(j.ok)save(q.id,v)}finally{setBusy(false)}}return <section className="q"><h2>{q.question}</h2><input value={v} disabled={!!answer} onChange={e=>setV(e.target.value)} placeholder="Javobni kiriting"/><Keypad on={x=>{if(!answer)setV(s=>s+x)}}/><button className="finish" disabled={!!answer||busy||!v.trim()} onClick={accept}>{answer?'Javob qabul qilingan':'Javobni qabul qilish'}</button></section>}
export default function Test(){const API=process.env.NEXT_PUBLIC_BACKEND_URL||'';const [qs,setQs]=useState([]),[answers,setAnswers]=useState({}),[results,setResults]=useState({}),[status,setStatus]=useState('loading'),[msg,setMsg]=useState(''),[score,setScore]=useState(null);const initData=typeof window!=='undefined'?window.Telegram?.WebApp?.initData||'':'';
useEffect(()=>{window.Telegram?.WebApp?.ready();window.Telegram?.WebApp?.expand();(async()=>{try{const [s,q]=await Promise.all([fetch(API+'/api/state?initData='+encodeURIComponent(initData)),fetch(API+'/api/questions')]);const list=await q.json();setQs(Array.isArray(list)?list:[]);if(!s.ok){setMsg('Test yopiq yoki Telegram sessiyasi topilmadi.');setStatus('blocked');return}const j=await s.json();if(!j.ok){setMsg(j.error||'Test yopiq');setStatus(j.error==='already_submitted'?'done':'blocked');return}setAnswers(j.answers||{});setStatus('test')}catch(e){setMsg('Server bilan aloqa yo‘q.');setStatus('blocked')}})()},[API,initData]);
async function choose(id,value){if(answers[id]!==undefined||status!=='test')return;const r=await fetch(API+'/api/answer',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData,question_id:id,answer:value})});const j=await r.json();if(j.ok){setAnswers(a=>({...a,[id]:value}));setResults(a=>({...a,[id]:j.correct?'correct':'wrong'}))}else if(j.error==='test_closed'){setStatus('expired');setMsg('Test yopildi. Yakunlanmagan urinish hisoblanmaydi.')}}
async function finish(){if(status!=='test')return;if(!confirm('Testni yakunlashni tasdiqlaysizmi?'))return;const r=await fetch(API+'/api/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({initData})});const j=await r.json();if(j.ok){setScore(j.score);setStatus('done');setMsg('Test muvaffaqiyatli yakunlandi.')}else{setStatus('expired');setMsg('Test yopilgan. Yakunlanmagan urinish hisoblanmaydi.')}}
function save(id,v){setAnswers(a=>({...a,[id]:v}))}
if(status==='loading')return <main className="center"><section className="panel"><b>NUR O‘QIW ORAYI</b><h1>Yuklanmoqda</h1></section></main>;
if(status==='blocked'||status==='done'||status==='expired')return <main className="center"><section className="panel"><b>NUR O‘QIW ORAYI</b><h1>{status==='done'?'Test yakunlandi':status==='expired'?'Test yopildi':'Test yopiq'}</h1><p>{msg}</p>{score!==null&&<strong className="final-score">{Number(score).toFixed(2)} ball</strong>}</section></main>;
return <><header><b>NUR O‘QIW ORAYI</b><span>{Object.keys(answers).length}/{qs.length}</span></header><main className="wrap"><section className="hero"><small>MILLIY SERTIFIKAT</small><h1>Matematika mock test</h1><p>{qs.length} ta savol</p></section>{qs.map(q=>q.kind==='written'?<Written key={q.id} q={q} answer={answers[q.id]} save={save} initData={initData}/>:<Choice key={q.id} q={q} answer={answers[q.id]} result={results[q.id]} onChoose={choose}/>)}</main><footer><span>{Object.keys(answers).length}/{qs.length}</span><button className="finish" onClick={finish}>Testni yakunlash</button></footer></>}
